version: '3.8'

services:
  my-node-app:
    image: kchosco29/my-node-app:latest
    container_name: my-node-app
    restart: unless-stopped
    ports:
      - "3000:3000"

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      # En Windows/WSL2 esta es la forma más estable
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # Forzamos a que use una versión de API moderna (acorde a tu versión 4.68)
      - DOCKER_API_VERSION=1.41 
      - WATCHTOWER_POLL_INTERVAL=30
      - WATCHTOWER_MONITOR_ONLY_CONTAINERS=my-node-app